version: 2.1
executors:
  docker-builder:
    environment:
      IMAGE_NAME: tomaka/cargo-apk
    docker:
      - image: docker:stable
jobs:
  build-and-test:
    executor: docker-builder
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
              root: .
              paths:
                - ./image.tar
  publish-docker-image:
    executor: docker-builder
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish final image
          command: |
            docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
            docker push IMAGE_NAME
workflows:
  version: 2
  all:
    jobs:
      - build-and-test
      - publish-docker-image:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
