[package]

name = "android_glue"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
license = "MIT"
description = "Glue for the Android JNI"
repository = "https://github.com/tomaka/android-rs-glue"
