[package]
name = "cargo-apk"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
license = "MIT"
description = "Cargo subcommand that allows you to build Android packages"

[dependencies]
rustc-serialize = "0.3.19"
toml = "0.1.28"
